apiVersion: apps/v1beta1
kind: Deployment
metadata:
  name: eventlistener-deployment
  labels:
    app: eventlistener
spec:
  replicas: 2
  selector:
    matchLabels:
      app: eventlistener
  template:
    metadata:
      labels:
        app: eventlistener
    spec:
      containers:
      - name: eventlistener
        image: shanepeckham/rabbitmqlistenerack:v5      
        ports:
        - containerPort: 8080
        env:
        - name: RABBITMQHOST
          value: amqp://team10:shambles@team10-rabbitmq
        - name: PROCESSENDPOINT
          value: http://fulfillorder:8080/v1/order/
        - name: TEAMNAME
          value: team10-ct


 