apiVersion: autoscaling/v1
kind: HorizontalPodAutoscaler
metadata:
  name: team10-hpa
  namespace: default
spec:
  maxReplicas: 15
  minReplicas: 3
  metrics:
  - type: Resource
    resource:
      name: cpu
      targetAverageUtilization: 50