apiVersion: autoscaling/v1
kind: HorizontalPodAutoscaler
metadata:
  name:
  namespace:
spec:
  maxReplicas: 15
  minReplicas: 3
  metrics:
  - type: Resource
    resource:
      name: cpu
      targetAverageUtilization: 50