apiVersion: autoscaling/v2beta1
kind: HorizontalPodAutoscaler
metadata:
  name: team10-hpa
  namespace: default
spec:
  scaleTargetRef:
    apiVersion: apps/v1beta1
    kind: Deployment
    name: captureorder-deployment
  maxReplicas: 15
  minReplicas: 3
  metrics:
  - type: Resource
    resource:
      name: cpu
      targetAverageUtilization: 50%